### ISSUE TITLE
Provision Omer w/ additional credentials

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/ob-iac#17]
github
ssh on instances
aws console/cli aceess
Add to Hass Nabu Casa and AWS via duckdns.

**Comment by angiedear** [comment]
Created account on Nabu Casa remote instance for Omer and provided credentials.

**Comment by angiedear** [comment]
@scottdear follow up to get Omer github access or ask Diego if we can get him access.

**Comment by angiedear** [comment]
Omer to get Ola public key for SSH.

**Comment by olagalal** [comment]
I waiting for Omar to send me ssh public key.

**Comment by angiedear** [comment]
Asked Diego to get Omer Github permissions.

**Comment by scottdear** [comment]
Can post AWS public key.

**Comment by olagalal** [comment]
Omar has access now to AWS
@scottdear @angiedear
