### ISSUE TITLE
Create repositories and check in source code

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/ob-iac#20]
Create repository for hardware and another for hass integrations.  Check in all source code to date in a way that makes sense.

**Comment by omerll** [comment]
https://github.com/oceanbuilders/Seapod-HA-V1
Here is the repo with all my HA config

**Comment by omerll** [comment]
New hardware and sofware diagrams uploded explaining how the system works, and also updated some files and code. check the same repo Seapod HA V1
