### ISSUE TITLE
Configure backup/restore - Design Doc

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/ob-iac#7]
Create Design Doc - On instance in AWS configure/setups backup/restore w/ Pod Instances.

Acceptance Criteria
----------------------
Design Documentation w/ Diagrams the describes the pieces required and implementation of backup/restore w/ Home Assistant and AWS.

**Comment by scottdear** [comment]
Large

**Comment by olagalal** [comment]
[Overview about Home Assistant Project](https://docs.google.com/document/d/1sWF4nqNyAeKLTEsMrBEDgK2Uzck9noY71FYwT_Yeuh8/edit?usp=sharing)

[Design Doc of Configuration of Backup/Restore](https://docs.google.com/document/d/1wXnUqfFsXgDOa4MwOJ1CgwjaEpZJ4_kTR0f7h-ba7X8/edit?usp=sharing)

**Comment by olagalal** [comment]
@scottdear please check if we can close this issue.

**Comment by angiedear** [comment]
Scott and Angie to Review before closing issue.
